### ISSUE TITLE
rename reset.scss to normalize.scss

### ISSUE THREAD

**Issue by j3ll3yfi5h** [miux/reset#2]

**Comment by marcwieland95** [comment]
Well, it's not per se just normalization. It's a mix.

But keep in mind that changing filenames could lead to problems on site which references directly to the filename. Sites embedded with NPM should point to "main" file, which also needs to be changed.

**Comment by marcwieland95** [comment]
@j3ll3yfi5h What's your opinion on that?

**Comment by marcwieland95** [comment]
@j3ll3yfi5h Can I close that? Your opinion?
